"""Interactive creation and editing of ``clusters.toml``.

``cluster-watcher setup`` walks the user through describing each machine and
writes a validated configuration. ``cluster-watcher config`` opens the existing
file in the user's editor and re-validates it afterwards. Both functions take
their input, output, and process-launching dependencies as parameters so they
can be unit tested without a terminal.
"""

from __future__ import annotations

import os
from pathlib import Path
import shutil
import subprocess
import tempfile
from typing import Callable, Mapping

from .config import load_config

Prompt = Callable[[str], str]
Output = Callable[[str], None]

HEADER = """\
# Generated by `cluster-watcher setup`. Edit with `cluster-watcher config`.
# This file is safe to commit: it contains connection identities, not passwords.
# SSH keys, agent forwarding, host verification, ProxyJump, etc. remain managed
# by your normal OpenSSH configuration.
# Add `hidden = true` to any machine entry to skip its login, polling, and display.
"""


def _toml_string(value: str) -> str:
    """Quote text as a TOML basic string."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render_config(machines: list[dict[str, object]]) -> str:
    """Serialize wizard answers as a commented ``clusters.toml`` document."""
    blocks = [HEADER]
    for machine in machines:
        lines = ["[[machine]]"]
        for key in ("name", "host", "username"):
            lines.append(f"{key} = {_toml_string(str(machine[key]))}")
        if machine.get("port", 22) != 22:
            lines.append(f"port = {int(machine['port'])}")
        if machine.get("identity_file"):
            lines.append(f"identity_file = {_toml_string(str(machine['identity_file']))}")
        if machine.get("interactive_auth"):
            lines.append("interactive_auth = true")
            if machine.get("credential_group"):
                lines.append(f"credential_group = {_toml_string(str(machine['credential_group']))}")
        roots = machine.get("job_log_roots") or []
        if roots:
            lines.append(f"job_log_roots = [{', '.join(_toml_string(str(root)) for root in roots)}]")
        blocks.append("\n".join(lines) + "\n")
    return "\n".join(blocks)


def _ask(prompt: Prompt, question: str, default: str | None = None, required: bool = True) -> str:
    """Ask until a non-empty answer (or the default) is available."""
    suffix = f" [{default}]" if default else ""
    while True:
        answer = prompt(f"{question}{suffix}: ").strip()
        if answer:
            return answer
        if default is not None:
            return default
        if not required:
            return ""


def _confirm(prompt: Prompt, question: str, default: bool = False) -> bool:
    """Ask a yes/no question, returning ``default`` for an empty answer."""
    hint = "Y/n" if default else "y/N"
    while True:
        answer = prompt(f"{question} [{hint}]: ").strip().lower()
        if not answer:
            return default
        if answer in {"y", "yes"}:
            return True
        if answer in {"n", "no"}:
            return False


def _ask_machine(prompt: Prompt, output: Output, taken: set[str], default_username: str) -> dict[str, object]:
    """Collect one ``[[machine]]`` entry."""
    while True:
        name = _ask(prompt, "Short machine name (e.g. cluster-a)")
        if name not in taken:
            break
        output(f"A machine named {name!r} already exists; choose another name.")
    machine: dict[str, object] = {
        "name": name,
        "host": _ask(prompt, "SSH host name"),
        "username": _ask(prompt, "Username", default_username or None),
    }
    while True:
        port = _ask(prompt, "SSH port", "22")
        if port.isdecimal() and 1 <= int(port) <= 65535:
            machine["port"] = int(port)
            break
        output("The port must be a number between 1 and 65535.")
    machine["identity_file"] = _ask(prompt, "SSH identity file (blank uses your OpenSSH defaults)", required=False)
    if _confirm(prompt, "Does this machine ask for a password or one-time code at login?"):
        machine["interactive_auth"] = True
        machine["credential_group"] = _ask(
            prompt, "Credential group shared with other machines using the same password (blank for none)",
            required=False,
        )
    roots = _ask(prompt, "Remote directories that may contain job logs, comma-separated (blank for none)", required=False)
    machine["job_log_roots"] = [root.strip() for root in roots.split(",") if root.strip()]
    return machine


def run_setup(
    path: Path,
    prompt: Prompt = input,
    output: Output = print,
    environ: Mapping[str, str] = os.environ,
) -> int:
    """Interactively build and atomically write a validated configuration."""
    output(f"Cluster Watcher setup will write {path}.")
    if path.exists() and not _confirm(prompt, f"{path} already exists. Replace it (a .bak copy is kept)?"):
        output("Setup cancelled; the existing configuration was not changed.")
        return 1
    machines: list[dict[str, object]] = []
    default_username = environ.get("USER", "")
    while True:
        output(f"\nMachine #{len(machines) + 1}")
        machine = _ask_machine(prompt, output, {str(item["name"]) for item in machines}, default_username)
        machines.append(machine)
        default_username = str(machine["username"])
        if not _confirm(prompt, "Add another machine?"):
            break
    text = render_config(machines)
    try:
        _write_validated(path, text)
    except ValueError as exc:
        output(f"The configuration was not written because it is invalid: {exc}")
        return 1
    output(f"\nWrote {path}. Run `cluster-watcher config` to fine-tune it, then `cluster-watcher status`.")
    return 0


def _write_validated(path: Path, text: str) -> None:
    """Validate ``text`` as a configuration, then replace ``path`` with it."""
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=".clusters-", suffix=".toml", dir=path.parent)
    try:
        with os.fdopen(descriptor, "w") as handle:
            handle.write(text)
        os.chmod(temporary, 0o600)
        load_config(Path(temporary))
        if path.exists():
            shutil.copy2(path, path.with_name(path.name + ".bak"))
        os.replace(temporary, path)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise


def find_editor(environ: Mapping[str, str] = os.environ, which: Callable[[str], str | None] = shutil.which) -> list[str]:
    """Return the user's editor command from ``$VISUAL``/``$EDITOR`` or a fallback."""
    for variable in ("VISUAL", "EDITOR"):
        value = environ.get(variable, "").strip()
        if value:
            return value.split()
    for candidate in ("nano", "vim", "vi"):
        if which(candidate):
            return [candidate]
    raise RuntimeError("no editor found; set $EDITOR (for example `export EDITOR=nano`)")


def edit_config(
    path: Path,
    prompt: Prompt = input,
    output: Output = print,
    environ: Mapping[str, str] = os.environ,
    run: Callable[[list[str]], object] = subprocess.run,
) -> int:
    """Open the configuration in an editor and re-validate it after each save."""
    if not path.exists():
        output(f"No configuration exists at {path}.")
        if _confirm(prompt, "Run the setup wizard now?", default=True):
            return run_setup(path, prompt, output, environ)
        return 1
    try:
        editor = find_editor(environ)
    except RuntimeError as exc:
        output(f"cluster-watcher: {exc}")
        return 1
    while True:
        run([*editor, str(path)])
        try:
            machines = load_config(path)
        except ValueError as exc:
            output(f"The configuration is invalid: {exc}")
            if _confirm(prompt, "Re-open the editor to fix it?", default=True):
                continue
            return 1
        output(f"{path} is valid ({len(machines)} visible machine(s)).")
        return 0
